services:
  postgres:
    image: postgres:16
    container_name: crazy_noisy_quiz_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crazy_noisy_quiz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
